<?php
declare(strict_types=1);

// BranchEvents SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BranchEventsUtility::setRegistrar(function (BranchEventsUtility $u): void {
    $u->clean = [BranchEventsClean::class, 'call'];
    $u->done = [BranchEventsDone::class, 'call'];
    $u->make_error = [BranchEventsMakeError::class, 'call'];
    $u->feature_add = [BranchEventsFeatureAdd::class, 'call'];
    $u->feature_hook = [BranchEventsFeatureHook::class, 'call'];
    $u->feature_init = [BranchEventsFeatureInit::class, 'call'];
    $u->fetcher = [BranchEventsFetcher::class, 'call'];
    $u->make_fetch_def = [BranchEventsMakeFetchDef::class, 'call'];
    $u->make_context = [BranchEventsMakeContext::class, 'call'];
    $u->make_options = [BranchEventsMakeOptions::class, 'call'];
    $u->make_request = [BranchEventsMakeRequest::class, 'call'];
    $u->make_response = [BranchEventsMakeResponse::class, 'call'];
    $u->make_result = [BranchEventsMakeResult::class, 'call'];
    $u->make_point = [BranchEventsMakePoint::class, 'call'];
    $u->make_spec = [BranchEventsMakeSpec::class, 'call'];
    $u->make_url = [BranchEventsMakeUrl::class, 'call'];
    $u->param = [BranchEventsParam::class, 'call'];
    $u->prepare_auth = [BranchEventsPrepareAuth::class, 'call'];
    $u->prepare_body = [BranchEventsPrepareBody::class, 'call'];
    $u->prepare_headers = [BranchEventsPrepareHeaders::class, 'call'];
    $u->prepare_method = [BranchEventsPrepareMethod::class, 'call'];
    $u->prepare_params = [BranchEventsPrepareParams::class, 'call'];
    $u->prepare_path = [BranchEventsPreparePath::class, 'call'];
    $u->prepare_query = [BranchEventsPrepareQuery::class, 'call'];
    $u->graphql_body = [BranchEventsGraphql::class, 'body'];
    $u->graphql_errors = [BranchEventsGraphql::class, 'errors'];
    $u->result_basic = [BranchEventsResultBasic::class, 'call'];
    $u->result_body = [BranchEventsResultBody::class, 'call'];
    $u->result_headers = [BranchEventsResultHeaders::class, 'call'];
    $u->transform_request = [BranchEventsTransformRequest::class, 'call'];
    $u->transform_response = [BranchEventsTransformResponse::class, 'call'];
});
